# Generated by Django 3.1.3 on 2020-11-10 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert the magazine name', max_length=100, verbose_name='Magazine name')),
                ('edition', models.IntegerField(help_text='Insert the magazine number', verbose_name='Magazine edition number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert your name', max_length=100, verbose_name='Full Name')),
                ('birth_date', models.DateField(help_text='Insert your birth date', verbose_name='Birth Date')),
                ('cpf', models.CharField(help_text='Insert your CPF number', max_length=11, verbose_name='CPF Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert the full name', max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Insert the professional email', max_length=254, verbose_name='Email')),
                ('cpf', models.CharField(help_text='Insert your CPF number', max_length=11, verbose_name='Insert the CPF Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(help_text='Insert your passport number', max_length=10, verbose_name='Passport Number')),
                ('issue_date', models.DateField(help_text='Insert the issue date of the passport.', verbose_name='Issue Date')),
                ('expiration_date', models.DateField(help_text='Insert the expiration date', verbose_name='Expiration Date')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meuapp.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insert the article title', max_length=100, verbose_name='Article title')),
                ('pub_date', models.DateTimeField(help_text='Insert the publication date time', verbose_name='Publication date')),
                ('magazines', models.ManyToManyField(help_text='Select magazines', to='meuapp.Magazine', verbose_name='Magazines')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description for your account', max_length=200)),
                ('number', models.CharField(help_text='Insert your account number here.', max_length=20)),
                ('balance', models.FloatField(default=0, help_text='Insert your initial balance.')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Account Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
